export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';
export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_PAGINATED_SUCCESS = 'GET_ALL_PRODUCTS_PAGINATED_SUCCESS';
export const GET_ALL_PRODUCTS_PAGINATED_FAILURE = 'GET_ALL_PRODUCTS_PAGINATED_FAILURE';

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";


export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE";
export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";

export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";
export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";

export const  DELETE_ITEM_SUCCESS = " DELETE_ITEM_SUCCESS";
export const  DELETE_ITEM_FAILURE = " DELETE_ITEM_FAILURE";
export const DELETE_ITEM_REQUEST = " DELETE_ITEM_REQUEST";

export const  FETCH_SHOPPING_CART_SUCCESS = "FETCH_SHOPPING_CART_SUCCESS";
export const  FETCH_SHOPPING_CART_FAILURE = "FETCH_SHOPPING_CART_FAILURE";
export const FETCH_SHOPPING_CART_REQUEST = "FETCH_SHOPPING_CART_REQUEST";


export const  FETCH_TOTAL_AMOUNT_CART_SUCCESS = "FETCH_TOTAL_AMOUNT_CART_SUCCESS";
export const  FETCH_TOTAL_AMOUNT_CART_FAILURE = "FETCH_TOTAL_AMOUNT_CART_FAILURE";
export const  FETCH_TOTAL_AMOUNT_CART_REQUEST= "FETCH_TOTAL_AMOUNT_CART_REQUEST";

export const FETCH_GENERATE_UNIQUE_CART_ID_SUCCESS = "FETCH_GENERATE_UNIQUE_CART_ID_SUCCESS";
export const FETCH_GENERATE_UNIQUE_CART_ID_FAILURE = "FETCH_GENERATE_UNIQUE_CART_ID_FAILURE";
export const FETCH_GENERATE_UNIQUE_CART_ID_REQUEST = "FETCH_GENERATE_UNIQUE_CART_ID_REQUEST";


export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const LOGOUT ='LOGOUT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const GET_PRODUCT_ATTRIBUTES = 'GET_PRODUCT_ATTRIBUTES';
export const GET_SHOPPING_CART_ID = 'GET_SHOPPING_CART_ID';
export const ADD_PRODUCTS_TO_CART = 'ADD_PRODUCTS_TO_CART';
export const GET_SHOPPING_CART_TOTAL = 'GET_SHOPPING_CART_TOTAL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const RESET_SUCCESS ='RESET_SUCCESS';
export const GET_SHOPPING_CART_ITEMS = 'GET_SHOPPING_CART_ITEMS';
export const UPDATE_SHOPPING_CART = 'UPDATE_SHOPPING_CART';
export const REMOVE_ITEM_SHOPPING_CART = 'REMOVE_ITEM_SHOPPING_CART';
export const EMPTY_SHOPPING_CART = 'EMPTY_SHOPPING_CART';
export const GET_TAXES = 'GET_TAXES';
export const GET_REGIONS = 'GET_REGIONS';
export const UPDATE_CUSTOMER_ADDRESS = 'UPDATE_CUSTOMER_ADDRESS';
export const CREATE_ORDER = 'CREATE_ORDER';
export const MAKE_PAYMENT = 'MAKE_PAYMENT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';





export const BASE_URL = 'https://backendapi.turing.com/';