export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS_SUCCESS';
export const ADD_PRODUCTS_FAILURE = 'ADD_PRODUCTS_FAILURE';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const LOGOUT ='LOGOUT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const GET_PRODUCT_ATTRIBUTES = 'GET_PRODUCT_ATTRIBUTES';
export const GET_SHOPPING_CART_ID = 'GET_SHOPPING_CART_ID';
export const ADD_PRODUCTS_TO_CART = 'ADD_PRODUCTS_TO_CART';
export const GET_SHOPPING_CART_TOTAL = 'GET_SHOPPING_CART_TOTAL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const RESET_SUCCESS ='RESET_SUCCESS';
export const GET_SHOPPING_CART_ITEMS = 'GET_SHOPPING_CART_ITEMS';
export const UPDATE_SHOPPING_CART = 'UPDATE_SHOPPING_CART';
export const REMOVE_ITEM_SHOPPING_CART = 'REMOVE_ITEM_SHOPPING_CART';
export const EMPTY_SHOPPING_CART = 'EMPTY_SHOPPING_CART';
export const GET_TAXES = 'GET_TAXES';
export const GET_REGIONS = 'GET_REGIONS';
export const UPDATE_CUSTOMER_ADDRESS = 'UPDATE_CUSTOMER_ADDRESS';
export const CREATE_ORDER = 'CREATE_ORDER';
export const MAKE_PAYMENT = 'MAKE_PAYMENT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';





export const BASE_URL = 'https://backendapi.turing.com/';